const express = require('express');
const { protect, authorize } = require('../middleware/auth');
const controller = require('../controllers/adminController');
const router = express.Router();
router.use(protect, authorize('admin'));
router.get('/users', controller.getUsers);
router.patch('/users/:id/status', controller.setUserStatus);
router.patch('/users/:id/role', controller.setUserRole);
router.patch('/users/:id/institution', controller.assignUserInstitution);
router.get('/institutions', controller.getInstitutions);
router.post('/institutions', controller.createInstitution);
router.get('/departments', controller.getDepartments);
router.post('/departments', controller.createDepartment);
router.get('/supervision', controller.getSupervisionOverview);
router.put('/projects/:projectId/supervisor', controller.assignProjectSupervisor);
module.exports = router;
