import { Link, useLocation } from 'react-router-dom';
import BrandLogo from '../components/BrandLogo';

const pages = {
  '/privacy': { title: 'Privacy Policy', intro: 'This page explains the information Supervisor Assistant needs to operate project supervision workflows.', sections: [['Information we process', 'Account identity, academic profile fields, project membership, tasks, submissions, feedback, meeting records, workspace documents, and security logs are processed to provide the service.'], ['How information is used', 'Information is used to authenticate users, enforce role permissions, connect students and supervisors, preserve academic decisions, and operate requested AI or integrity features.'], ['Your choices', 'You may update profile information and contact the platform administrator about access, correction, retention, or deletion requests. Academic records may need to be retained under institutional policy.']] },
  '/terms': { title: 'Terms of Service', intro: 'These terms define responsible use of the academic project workspace.', sections: [['Academic responsibility', 'Users remain responsible for the accuracy, originality, citation quality, and final submission of their academic work. AI output is assistance, not approval or authorship.'], ['Acceptable use', 'Do not attempt unauthorized access, upload harmful content, misuse another person’s identity, or use the service to violate academic or institutional rules.'], ['Service availability', 'Compiler, code execution, AI, email, and literature services may depend on separately configured providers and can be temporarily unavailable.']] },
  '/data-processing': { title: 'Data Processing Notice', intro: 'This notice summarizes the service’s roles and safeguards for academic data.', sections: [['Processing scope', 'The application processes data necessary for project membership, supervision, submissions, feedback, meetings, reporting, and audit history.'], ['Third-party services', 'When configured, selected content may be sent to infrastructure, email, AI, compiler, literature metadata, or integrity providers. Administrators should review each provider before enabling it.'], ['Security and retention', 'The service uses authenticated APIs and role-based project authorization. Administrators are responsible for deployment secrets, provider contracts, retention settings, backups, and incident response.']] }
};

export default function LegalPage() {
  const page = pages[useLocation().pathname] || pages['/privacy'];
    return <main className="min-h-screen bg-background px-5 py-8 text-on-surface"><div className="mx-auto max-w-4xl"><Link to="/" className="inline-flex rounded-2xl border border-outline-variant bg-surface px-4 py-3"><BrandLogo className="h-8 w-auto" /></Link><article className="mt-8 rounded-[32px] border border-outline-variant/35 bg-surface p-7 shadow-sm md:p-12"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Supervisor Assistant</p><h1 className="mt-3 text-4xl font-black">{page.title}</h1><p className="mt-3 text-sm text-secondary">Effective August 18, 2026</p><p className="mt-8 text-lg leading-8 text-on-surface-variant">{page.intro}</p><div className="mt-10 space-y-8">{page.sections.map(([title, body]) => <section key={title}><h2 className="text-xl font-black">{title}</h2><p className="mt-2 leading-7 text-on-surface-variant">{body}</p></section>)}</div><p className="mt-10 rounded-2xl bg-surface-container-low p-4 text-sm text-secondary">This deployment notice should be reviewed and customized by the operating institution before production use. Contact <a href="mailto:suprevisorassistant@gmail.com" className="text-primary hover:underline">suprevisorassistant@gmail.com</a> for support.</p></article></div></main>;
}
