import { useEffect, useState } from 'react';
import { apiFetch } from '../lib/api';
import { useAuth } from '../components/AuthContext';

const Profile = () => {
  const { updateUser } = useAuth(); const [profile, setProfile] = useState(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { apiFetch('/api/users/profile').then((result) => setProfile(result.data)).catch((requestError) => setError(requestError.message)); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); setMessage(''); setError(''); try { const result = await apiFetch('/api/users/profile', { method: 'PUT', body: JSON.stringify(profile) }); setProfile(result.data); updateUser(result.data); setMessage('Profile saved.'); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  if (!profile) return <div className="grid min-h-[60vh] place-items-center text-secondary">Loading profile…</div>;
  return <main className="mx-auto max-w-3xl p-6 md:p-10"><p className="text-xs font-bold uppercase tracking-widest text-primary">Account</p><h1 className="mt-2 text-3xl font-extrabold text-on-surface">My profile</h1><p className="mt-2 text-secondary">Keep your academic identity up to date. Password changes are handled through the reset-password link.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-error/10 p-3 text-sm text-error">{error}</p>}{message && <p role="status" className="mt-5 rounded-xl bg-emerald-500/10 p-3 text-sm text-emerald-700">{message}</p>}<form onSubmit={save} className="mt-6 grid gap-5 rounded-2xl border border-outline-variant/30 bg-surface p-6 shadow-sm sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-bold text-on-surface">Full name<input required value={profile.name || ''} onChange={(event) => setProfile({ ...profile, name: event.target.value })} className="mt-2 w-full rounded-xl border border-outline-variant/50 bg-surface-container-lowest px-3 py-3 font-normal outline-none focus:border-primary" /></label><label className="text-sm font-bold text-on-surface">Email<input disabled value={profile.email || ''} className="mt-2 w-full rounded-xl border border-outline-variant/30 bg-surface-container-low px-3 py-3 font-normal text-secondary" /></label><label className="text-sm font-bold text-on-surface">Role<input disabled value={profile.role || ''} className="mt-2 w-full rounded-xl border border-outline-variant/30 bg-surface-container-low px-3 py-3 font-normal capitalize text-secondary" /></label><label className="text-sm font-bold text-on-surface">Department<input value={profile.department || ''} onChange={(event) => setProfile({ ...profile, department: event.target.value })} className="mt-2 w-full rounded-xl border border-outline-variant/50 bg-surface-container-lowest px-3 py-3 font-normal outline-none focus:border-primary" /></label><label className="text-sm font-bold text-on-surface">Student ID<input value={profile.studentId || ''} onChange={(event) => setProfile({ ...profile, studentId: event.target.value })} className="mt-2 w-full rounded-xl border border-outline-variant/50 bg-surface-container-lowest px-3 py-3 font-normal outline-none focus:border-primary" /></label><button disabled={saving} className="sm:col-span-2 justify-self-end rounded-xl bg-primary px-5 py-3 text-sm font-bold text-on-primary disabled:opacity-60">{saving ? 'Saving…' : 'Save profile'}</button></form></main>;
};

export default Profile;
